"""
Email sender — send Markus pipeline results via SMTP.

Provides:
- ``build_html_table()`` — format result rows as an HTML table
- ``send_results_email()`` — build and dispatch an HTML email with optional CSV attachment

Inspired by the Agent Demo ``email_sender.py``.
"""

from __future__ import annotations

import logging
import smtplib
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path
from typing import Any

from config import config

logger = logging.getLogger(__name__)

# ── Column mapping — Markus record keys → display labels ──────────────────

COLUMN_LABELS: list[tuple[str, str]] = [
    ("company_name", "Company"),
    ("ceo_name", "CEO"),
    ("ceo_linkedin_url", "CEO LinkedIn"),
    ("cfo_name", "CFO"),
    ("cfo_linkedin_url", "CFO LinkedIn"),
    ("director_general_name", "Director General"),
    ("director_general_linkedin_url", "Director General LinkedIn"),
    ("job_source_url", "Job Source"),
    ("search_keyword", "Keyword"),
]


def build_html_table(rows: list[dict[str, str]]) -> str:
    """Build an HTML table from Markus result rows.

    Parameters
    ----------
    rows : list[dict[str, str]]
        Records with keys matching the Markus output schema
        (``company_name``, ``ceo_name``, ``ceo_linkedin_url``, etc.).

    Returns
    -------
    str
        An HTML ``<table>`` element.
    """
    if not rows:
        return "<p>No results found.</p>"

    cells: list[str] = []
    cells.append(
        "<table border='1' cellpadding='6' cellspacing='0' "
        "style='border-collapse:collapse; font-family:sans-serif; width:100%;'>"
    )
    cells.append("<thead style='background:#005fcc; color:white;'>")
    cells.append("<tr>")
    cells.append("<th>#</th>")
    for _, label in COLUMN_LABELS:
        cells.append(f"<th>{label}</th>")
    cells.append("</tr>")
    cells.append("</thead>")
    cells.append("<tbody>")

    for i, row in enumerate(rows, 1):
        bg = "#f5f5f5" if i % 2 == 0 else "#ffffff"
        cells.append(f"<tr style='background:{bg}'>")
        cells.append(f"<td>{i}</td>")
        for key, _ in COLUMN_LABELS:
            val = row.get(key, "")
            # Turn URLs into clickable links
            if val and key.endswith("_url"):
                cells.append(f"<td><a href='{val}'>{val}</a></td>")
            else:
                cells.append(f"<td>{val}</td>")
        cells.append("</tr>")

    cells.append("</tbody>")
    cells.append("</table>")
    return "\n".join(cells)


def send_results_email(
    to_email: str,
    subject: str,
    rows: list[dict[str, str]],
    csv_path: str | None = None,
) -> None:
    """Send an HTML email with a results table and optional CSV attachment.

    Parameters
    ----------
    to_email : str
        Recipient email address.
    subject : str
        Email subject line.
    rows : list[dict[str, str]]
        Markus result records to display in the HTML table.
    csv_path : str, optional
        Path to a CSV file to attach (generated by the Markus pipeline).

    Raises
    ------
    ValueError
        If SMTP is not configured in environment variables.
    smtplib.SMTPException
        If the SMTP server rejects the message.
    """
    if not config.smtp_configured:
        raise ValueError(
            "SMTP not configured. Set SMTP_HOST, SMTP_USER, "
            "SMTP_PASSWORD, and EMAIL_FROM in .env"
        )

    # ── Build the MIME message ────────────────────────────────────────────
    msg = MIMEMultipart("mixed")
    msg["From"] = config.email_from
    msg["To"] = to_email
    msg["Subject"] = subject

    # ── HTML body ─────────────────────────────────────────────────────────
    html_table = build_html_table(rows)
    html_body = f"""<!DOCTYPE html>
<html>
<head><meta charset='utf-8'></head>
<body style='font-family:sans-serif; max-width:960px; margin:20px auto;'>
    <h2 style='color:#005fcc;'>🤖 Markus — Search Results</h2>
    <p>Found <strong>{len(rows)}</strong> records with company and executive data.</p>
    {html_table}
    <hr style='margin-top:20px;'>
    <p style='color:#666; font-size:12px;'>Generated by Markus</p>
</body>
</html>"""
    msg.attach(MIMEText(html_body, "html", "utf-8"))

    # ── CSV attachment (optional) ─────────────────────────────────────────
    if csv_path:
        csv_file = Path(csv_path)
        if csv_file.exists():
            with open(csv_file, "rb") as f:
                attachment = MIMEApplication(f.read(), _subtype="csv")
                attachment.add_header(
                    "Content-Disposition",
                    "attachment",
                    filename=csv_file.name,
                )
                msg.attach(attachment)

    # ── Send via SMTP ────────────────────────────────────────────────────
    with smtplib.SMTP(config.smtp_host, config.smtp_port, timeout=30) as server:
        server.starttls()
        server.login(config.smtp_user, config.smtp_password)
        server.send_message(msg)

    logger.info("Email sent to %s (%d rows)", to_email, len(rows))
